document.addEventListener("DOMContentLoaded", () => {
    const translations = {

        fr: {
            "welcome-title": "Bienvenue sur Pro IN Deutsch",
            "welcome-text": "Apprenez l'allemand de manière efficace et interactive, avec des cours entièrement en ligne adaptés à tous les niveaux !",
            "payment-title": "Options de paiement",
            "payment-text": "Choisissez votre niveau et commencez dès aujourd'hui :",
            "contact-title": "Contactez-nous",
            "contact-text": "Envoyez-nous vos informations si vous êtes intéressé(e) :",
            "about-title": "Pourquoi choisir Pro IN Deutsch ?",
            "about-text": "Nous sommes spécialisés dans l'enseignement de l'allemand avec des professeurs certifiés.",
            "site-title": "Pro IN Deutsch" ,
            "nav-home": "Accueil",
            "nav-payment": "Paiement",
            "nav-contact": "Contact",
            "nav-about": "Pourquoi nous?",
            "footer-copyright": "© 2024 Pro IN Deutsch - Tous droits réservés.",
            "footer-follow": "Suivez-nous sur :",
            "info": "Contactez-nous : proindeutsch@gmail.com | Téléphone : +4917673977056 (Whatsapp)",
            "nom": "Nom : ",
            "email": "Email : ",
            "phone": "Numéro de téléphone :",
            "sms": "Message : ",
            "envoyer": " Envoyer ",
            "savoir": " En Savoir plus ",
            "cour": " Nos Cours de Langue Allemande ",
            "online1": "100% en ligne",
            "online2": "Apprenez à votre rythme, partout où vous êtes.",
            "frequenz1": "Fréquence",
            "frequenz2": "2 heures / jour.  3 jours par semaine, pour un apprentissage régulier et efficace.",
            "group1": "Groupe ou individuel",
            "group2": "Choisissez la formule qui vous convient : en groupe ou seul à seul.",
            "recom1": "Gagnez 10€ pour chaque recommandation !",
            "recom2": "Recommandez nos cours à vos amis et gagnez une prime pour chaque inscription pour deux mois au minimum grâce à vous.",
            "decouv1": "Découvrez l'apprentissage de l'allemand",
            "decouv2": "Cliquez sur l'image pour regarder la vidéo sur YouTube.", 
            "quest0": "Questions Fréquentes",
            "quest1": " Quels sont les niveaux proposés ?",
            "rep1": "Nous proposons les niveaux A1(A1.1 & A1.2), A2(A2.1 & A2.2), B1(B1.1 & B1.2), B2(B2.1 & B2.2) et C1",
            "quest2": "Les cours sont-ils en ligne ou en présentiel ?",
            "rep2": "Nos cours sont entièrement en ligne, ce qui vous permet d'apprendre de n'importe où. ",
            "quest3": " Puis-je suivre les cours en groupe ou individuellement ?",
            "rep3": "Oui, vous pouvez choisir entre des cours en groupe ou des cours privés, selon ce qui vous convient le mieux.",
            "quest4": " Avez-vous des Document que vous proposez ?",
            "rep4": "Nous avons beaucoup de documents (Redemittel, éxercices...) en Pdf ainsi que des livres tels que A_Grammatik, B_Grammatik et C_Grammatik. Nous avons aussi des livres en Pdf de préparation aux examens officiels comme la gamme 'Mit erfolg' et bien d'autres gammes.",
            "quest5": " À quels examens préparez vous et que faut-il faire ?",
            "rep5": "Inscrivez-vous à un examen officiel dans la ville de votre choix et prévoyez au moins 1 mois de préparation. Nous préparons aux examens tel que Telc A1-C1, Goethe Zertifikat A1-C1 et DSH C1 de toutes les villes de l'allemagne.",
            "quest6": "Quel Matériel faut-il pour commencer ?",
            "rep6": "Il vous faut un ordinateur et pas un téléphone parcequ'il faudra pouvoir lire le texte lors du partage d'écran pendant le cours. L'écran du téléphone est trop petit pour pouvoir bien lire lors du partage d'écran. Il vous faut une connexion internet stable, si possible une imprimante pour pouvoir imprimer les Pdf et ensuite écrire dessus et au mieux une tabette numérique pour pouvoir écrire sur les Pdfs ou écrire du texte qui pourra être envoyé facilement sans avoir besoin de scanner le texte écrit sur papier. Il vous faut aussi installer l'application Télegram pour pouvoir échanger des données. Ou encore installer Adobe Scan ou Camscanner sur votre téléphone pour scanner les textes écrits.",
            "quest7": " Que faut-il pour débuter avec les cours de langue ?",
            "rep7": "Pour commencer lisez bien questions fréquentes et Contactez-nous au +4917673977056 (sur Whatsapp) avec une date de début et le niveau qui vous intéresse.",
            "quest8": "Pour quel type de cours de langue devrait-on vous contacter ?",
            "rep8": "Vous Pouvez nous contacter pour tous types de cours de langue pourvu qu'il s'agisse de l'allemand et qu'il ne s'agisse pas d'enfant. Vous pouvez nous contacter juste si vous voulez améliorer votre allemand ou pour le boulot.",
            "quest9": "Est-ce que l'on peut travailler depuis l'Afrique ?",
            "rep9": "Vous pouvez travailler de n'importe òu pourvu que vous ayez une bonne connection internet et vous devez être prêt à payer le prix qu'il faut. Allez sur la page de paiement pour le prix.",
            "quest10": "Comment faire pour payer ?",
            "rep10": "Allez sur l'onglet paiement pour plus d'informations",
            "quest11": "Est-t'il possible d'être remboursé ?",
            "rep11": "Si après un jour vous n'êtes pas interéssé alors on vous remboursera entièrement. À plus de 1 jour on vous facturera le temps passé.",
            "quest12": "Est-ce qu'il y'a un test de niveau ?",
            "rep12": "Il y'a un test de niveau lorsque nous travaillons. Si pendant la première semaine nous constatons que le niveau de l'élève est très bas, alors il y'aura 50 Eur supplémentaire à payer sauf pour les niveaux A1.1 et A1.2.",
            "hour1": "24 heures",
            "hour2": "24 heures",
            "hour3": "24 heures",
            "hour4": "24 heures",
            "hour5": "24 heures",
            "hour": "24 heures",
            "debut": "Débutant",
            "elemt": "Elementaire",
            "inter": "Intermédiaire",
            "avan": "Avancé",
            "prof": "Professionnel",
            "prim": "Prime de recommandation",
            "proc": "Comment procéder au paiement",
            "par0": "Le paiement peut se faire en 2 tranches : Par exemple, la première tranche du niveau A1.1 coûte 120 Euros et la deuxième tranche coûte 100 Euros. La deuxième tranche se paye 2 semaines après la première.",
            "par3": "Modes de paiement",
            "par4": "Notez bien : Fournissez le niveau qui vous intéresse lors du paiement et renseignez-vous d'abord sur votre date de début de cours avant de payer.",
            "par5": "Fournissez le niveau qui vous intéresse lors du paiement et renseignez-vous d'abord sur votre date de début de cours avant de payer. ",
            "par6": "Faites un don pour soutenir notre projet",
            "par7": "Nous avons des écoles à construire en Afrique. Vos dons vont permettre d'offrir un apprentissage de qualité accessible à tous.",
            "par8": "Faire un don via PayPal",
            "vir": "Virement bancaire :",
            "n1": "Nom :",
            



        },
        en: {
            "welcome-title": "Welcome to Pro IN Deutsch",
            "welcome-text": "Discover our German language courses tailored for all levels, from beginner to advanced.",
            "payment-title": "Payment Options",
            "payment-text": "Here are the prices for each level. One level, for example B1.1, lasts 1 month.",
            "contact-title": "Contact Us",
            "contact-text": "Send us your details if you're interested:",
            "about-title": "Why choose Pro IN Deutsch?",
            "about-text": "We specialize in teaching German with certified teachers.",
            "site-title": "Pro IN Deutsch",
            "nav-home": "Home",
            "nav-payment": "Payment",
            "nav-contact": "Contact",
            "nav-about": "Why us?",
            "footer-copyright": "© 2024 Pro IN Deutsch - All rights reserved.",
            "footer-follow": "Follow us on:",
             "info": "Contact us: proindeutsch@gmail.com | Phone:  +4917673977056 (Whatsapp)",
             "nom": "Name : ",
            "email": "Email : ",
            "phone": "Phone number :",
            "sms":  "Text : ",
            "envoyer": "  Send  ",
            "savoir": " Learn more ",
            "cour": " Our German Language Courses ",
            "online1": "100% Online",
            "online2": "Learn at your own pace, wherever you are.",
            "frequenz1": "Frequency",
            "frequenz2": "2 hours / day.  3 days a week, for regular and effective learning.",
            "group1": "Group or individual",
            "group2": "Choose the option that suits you best: in a group or one-on-one.",
            "recom1": "Earn €10 for each referral!",
            "recom2": "Recommend our courses to your friends and earn a bonus for each registration of at least two months thanks to you.",
            "decouv1": "Discover learning German",
            "decouv2": "Click on the image to watch the video on YouTube.", 
            "quest0": "Frequently Asked Questions",
            "quest1": "What levels are offered?",
            "rep1": "We offer levels A1 (A1.1 & A1.2), A2 (A2.1 & A2.2), B1 (B1.1 & B1.2), B2 (B2.1 & B2.2), and C1.",
            "quest2": "Are the courses online or in-person?",
            "rep2": "Our courses are fully online, allowing you to learn from anywhere.",
            "quest3": "Can I take the courses in a group or individually?",
            "rep3": "Yes, you can choose between group courses or private lessons, depending on what suits you best.",
            "quest4": "Do you provide any materials?",
            "rep4": "We have plenty of materials (Redemittel, exercises...) in PDF format, as well as books like A_Grammatik, B_Grammatik, and C_Grammatik. We also offer PDF books for official exam preparation, such as the 'Mit Erfolg' series and many others.",
            "quest5": "Which exams do you prepare for, and what are the steps?",
            "rep5": "Register for an official exam in the city of your choice and allow at least 1 month for preparation. We prepare for exams such as Telc A1-C1, Goethe Zertifikat A1-C1, and DSH C1 in all cities in Germany.",
            "quest6": "What equipment is needed to start?",
            "rep6": "You need a computer, not a phone, because you'll need to read texts during screen sharing in class. A phone screen is too small for this purpose. You’ll also need a stable internet connection, preferably a printer to print PDFs and write on them, and ideally a digital tablet to write on PDFs or send written text easily without scanning paper documents. You should also install the Telegram app to exchange data or install Adobe Scan or Camscanner on your phone to scan written texts.",
            "quest7": "What do I need to start language lessons?",
            "rep7": "To start, carefully read the frequently asked questions and contact us at +4917673977056 (on WhatsApp) with a start date and the level you’re interested in.",
            "quest8": "For what type of language courses should I contact you?",
            "rep8": "You can contact us for any type of German language course as long as it’s not for children. You can contact us whether you just want to improve your German or for work purposes.",
            "quest9": "Can someone work from Africa?",
            "rep9": "You can work from anywhere as long as you have a good internet connection and are ready to pay the required price. Go to the payment page for pricing information.",
            "quest10": "How can I make a payment?",
            "rep10": "Go to the payment tab for more information.",
            "quest11": "Is it possible to get a refund?",
            "rep11": "If after one day you’re not interested, we will refund you fully. After more than one day, you will be charged for the time spent.",
            "quest12": "Is there a placement test?",
            "rep12": "There is a placement test while we work. If during the first week we notice that the student’s level is very low, there will be an additional €50 fee, except for levels A1.1 and A1.2.",
            "hour1": "24 hours",
            "hour2": "24 hours",
            "hour3": "24 hours",
            "hour4": "24 hours",
            "hour5": "24 hours",
            "debut": "Beginner",
            "elemt": "Elementary",
            "inter": "Intermediate",
             "avan": "Advanced",
            "prof": "Professional",
            "prim": "Referral bonus",
            "proc": "How to proceed with the payment",
            "par0": "The payment can be made in 2 installments: For example, the first installment for level A1.1 costs 120 Euros, and the second installment costs 100 Euros. The second installment is paid 2 weeks after the first. ",
            "par3": "Payment methods",
            "par4": "Please note: Provide the level you are interested in when making the payment, and check your course start date before paying.",
            "par6": "Make a donation to support our project",
            "par7": "We have schools to build in Africa. Your donations will help provide quality learning accessible to everyone.",
            "par8": "Donate via PayPal",
            "vir": "Bank transfer:",
            "n1": "Name:",


            
        },
        de: {
            "welcome-title": "Willkommen bei Pro IN Deutsch",
            "welcome-text": " Lernen Sie Deutsch effektiv und interaktiv mit vollständig online angebotenen Kursen, die für alle Niveaus geeignet sind!",
            "payment-title": "Zahlungsoptionen",
            "payment-text": "Hier sind die Preise für jedes Niveau. Ein Niveau, zum Beispiel B1.1, dauert 1 Monat.",
            "contact-title": "Kontaktieren Sie uns",
            "contact-text": "Senden Sie uns Ihre Informationen, wenn Sie interessiert sind:",
            "about-title": "Warum Pro IN Deutsch wählen?",
            "about-text": "Wir sind spezialisiert auf das Unterrichten von Deutsch mit zertifizierten Lehrern.",
            "site-title": "Pro IN Deutsch",
            "nav-home": "Startseite",
            "nav-payment": "Bezahlung",
            "nav-contact": "Kontakt",
            "nav-about": "Warum wir?",
            "footer-copyright": "© 2024 Pro IN Deutsch - Alle Rechte vorbehalten.",
            "footer-follow": "Folgen Sie uns auf:",
             "info": "Kontaktieren Sie uns: proindeutsch@gmail.com | Telefon: +4917673977056 (Whatsapp)",
             "nom": "Name : ",
            "email": "Email : ",
            "phone": "Telefonnummer :",
            "sms": "Nachricht : ",
            "envoyer": " Senden ",
            "savoir": " Mehr erfahren ",
            "cour": " Unsere Deutschkurse ",
            "online1": "100% Online",
            "online2": "Lernen Sie in Ihrem eigenen Tempo, egal wo Sie sind.",
            "frequenz1": "Frequenz",
            "frequenz2": "2 Stunden / Tag.  3 Tage pro Woche, für ein regelmäßiges und effektives Lernen.",
            "group1": "Gruppe oder Einzelperson",
            "group2": "Wählen Sie die Option, die Ihnen am besten passt: in der Gruppe oder im Einzelgespräch.",
            "recom1": " Verdienen Sie 10 € für jede Empfehlung!",
            "recom2": "Empfehlen Sie unsere Kurse Ihren Freunden und erhalten Sie eine Prämie für jede Anmeldung von mindestens zwei Monaten dank Ihnen.",
            "decouv1": "Entdecken Sie das Erlernen der deutschen Sprache",
            "decouv2": "Klicken Sie auf das Bild, um das Video auf YouTube anzusehen.", 
            "quest0": "Häufig gestellte Fragen",
            "quest1": "Welche Niveaus werden angeboten?",
            "rep1": "Wir bieten die Niveaus A1 (A1.1 & A1.2), A2 (A2.1 & A2.2), B1 (B1.1 & B1.2), B2 (B2.1 & B2.2) und C1 an.",
            "quest2": "Sind die Kurse online oder vor Ort?",
            "rep2": "Unsere Kurse sind komplett online, sodass Sie von überall aus lernen können.",
            "quest3": "Kann ich die Kurse in einer Gruppe oder individuell belegen?",
            "rep3": "Ja, Sie können zwischen Gruppenkursen oder Einzelunterricht wählen, je nachdem, was für Sie am besten passt.",
            "quest4": "Stellen Sie Materialien zur Verfügung?",
            "rep4": "Wir haben viele Materialien (Redemittel, Übungen...) im PDF-Format sowie Bücher wie A_Grammatik, B_Grammatik und C_Grammatik. Wir bieten auch PDF-Bücher zur Vorbereitung auf offizielle Prüfungen wie die 'Mit Erfolg'-Reihe und viele andere an.",
            "quest5": "Auf welche Prüfungen bereiten Sie vor, und was muss man tun?",
            "rep5": "Melden Sie sich für eine offizielle Prüfung in der Stadt Ihrer Wahl an und planen Sie mindestens einen Monat für die Vorbereitung ein. Wir bereiten auf Prüfungen wie Telc A1-C1, Goethe-Zertifikat A1-C1 und DSH C1 in allen Städten Deutschlands vor.",
            "quest6": "Welche Ausstattung wird benötigt, um zu starten?",
            "rep6": "Sie benötigen einen Computer, kein Telefon, da Sie während des Bildschirmteilens im Unterricht Texte lesen müssen. Der Bildschirm eines Telefons ist dafür zu klein. Sie benötigen außerdem eine stabile Internetverbindung, idealerweise einen Drucker, um PDFs auszudrucken und darauf zu schreiben, sowie idealerweise ein Grafiktablett, um auf PDFs zu schreiben oder Texte zu versenden, ohne Papierdokumente scannen zu müssen. Sie sollten auch die Telegram-App installieren, um Daten auszutauschen, oder Adobe Scan oder Camscanner auf Ihrem Telefon, um handschriftliche Texte zu scannen.",
            "quest7": "Was brauche ich, um mit dem Sprachkurs zu beginnen?",
            "rep7": "Lesen Sie die häufig gestellten Fragen sorgfältig durch und kontaktieren Sie uns unter +4917673977056 (auf WhatsApp) mit einem Startdatum und dem Niveau, das Sie interessiert.",
            "quest8": "Für welche Sprachkurse sollte man Sie kontaktieren?",
            "rep8": "Sie können uns für alle Arten von Deutschkursen kontaktieren, solange es sich nicht um Kinderkurse handelt. Kontaktieren Sie uns, wenn Sie Ihr Deutsch verbessern möchten oder für berufliche Zwecke.",
            "quest9": "Kann man von Afrika aus arbeiten?",
            "rep9": "Sie können von überall aus arbeiten, solange Sie eine gute Internetverbindung haben und bereit sind, den erforderlichen Preis zu zahlen. Gehen Sie auf die Zahlungsseite, um die Preise zu erfahren.",
            "quest10": "Wie kann ich bezahlen?",
            "rep10": "Gehen Sie auf die Zahlungsseite für weitere Informationen.",
            "quest11": "Ist eine Rückerstattung möglich?",
            "rep11": "Wenn Sie nach einem Tag nicht interessiert sind, erstatten wir Ihnen den vollen Betrag. Nach mehr als einem Tag berechnen wir die verbrachte Zeit.",
            "quest12": "Gibt es einen Einstufungstest?",
            "rep12": "Es gibt einen Einstufungstest während des Unterrichts. Wenn wir in der ersten Woche feststellen, dass das Niveau des Schülers sehr niedrig ist, fallen zusätzlich 50 Euro an, außer für die Niveaus A1.1 und A1.2.",
            "hour1": "24 Stunden",
            "hour2": "24 Stunden",
            "hour3": "24 Stunden",
            "hour4": "24 Stunden",
            "hour5": "24 Stunden",
            "debut": "Anfänger",
            "elemt": "Elementar",
            "inter": "Mittelstufe",
            "avan": "Fortgeschritten",
            "prof": "Professionell",
            "prim": "Empfehlungsprämie",
            "proc": "Wie man mit der Zahlung fortfährt",
            "par0": "Die Zahlung kann in 2 Raten erfolgen: Zum Beispiel kostet die erste Rate für das Niveau A1.1 120 Euro und die zweite Rate 100 Euro. Die zweite Rate wird 2 Wochen nach der ersten bezahlt.",
            "par3": "Zahlungsmethoden",
            "par4": "Bitte beachten Sie: Geben Sie das Niveau an, das Sie interessiert, wenn Sie die Zahlung vornehmen, und erkundigen Sie sich vor der Zahlung nach Ihrem Kursstartdatum.",
            "par6": "Spenden Sie, um unser Projekt zu unterstützen",
            "par7": "Wir haben Schulen in Afrika zu bauen. Ihre Spenden werden helfen, eine qualitativ hochwertige Bildung für alle zugänglich zu machen.",
            "par8": "Spenden über PayPal",
            "vir": "Banküberweisung:",
            "n1": "Name:",


        }
    };

    document.getElementById("language-selector").addEventListener("change", (event) => {
        const lang = event.target.value;
        for (const [key, translation] of Object.entries(translations[lang])) {
            const element = document.getElementById(key);
            if (element) element.textContent = translation;
        }
    });

    
});
